server:
  port: 7001

# Eureka的配置
eureka:
  instance:
    hostname: localhost  # Eureka服务端的实列名称
  client:
    register-with-eureka: false  # 表示是否向eureka注册中心注册自己（服务器不用注册自己）
    fetch-registry: false  # 如果fetch-registry为false,表示自己为注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  # 这就是监控页面地址：hostname和port(端口）都是从配置文件中动态获取的