server:
  port: 9527
spring:
  application:
    name: springcloud-zuul  # 微服务的名字
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true # 详细信息显示ip
info:
  app.name: msj-springcloud
  company.name: msj.com

# zuul的配置
zuul:
  routes:  # routes是Map（键值对），我们可以随意配置
    mydept:
      serviceId: springcloud-provider-dept
      path: /mydept/**
  ignored-services: springcloud-provider-dept # 不能再使用这个路径访问了
  prefix: /msj
